// Action types
export const FETCH_DEONAR_DETAILS_SUCCESS = 'FETCH_DEONAR_DETAILS_SUCCESS';
export const FETCH_STAKEHOLDER_DETAILS_SUCCESS = 'FETCH_STAKEHOLDER_DETAILS_SUCCESS';
export const SAVE_DEONAR_DETAILS_SUCCESS = 'SAVE_DEONAR_DETAILS_SUCCESS';
export const SAVE_DEONAR_DETAILS_FAILURE = 'SAVE_DEONAR_DETAILS_FAILURE';
export const FETCH_DEONAR_ENTRY_FEE_DETAILS_SUCCESS = 'FETCH_DEONAR_ENTRY_FEE_DETAILS_SUCCESS'