

CREATE TABLE IF NOT EXISTS eg_bmc_application_snapshot (
	id serial4 NOT NULL,
	housenobldgapt varchar(32) NULL,
	subdistrict varchar(100) NULL,
	postoffice varchar(100) NULL,
	landmark varchar(256) NULL,
	country varchar(50) NULL,
	"type" varchar(50) NULL,
	streetroadline varchar(256) NULL,
	citytownvillage varchar(256) NULL,
	arealocalitysector varchar(256) NULL,
	district varchar(100) NULL,
	state varchar(100) NULL,
	pincode varchar(10) NULL,
	aadharref varchar(12) NULL,
	aadharfathername varchar(255) NULL,
	aadharname varchar(255) NULL,
	aadharmobile varchar(15) NULL,
	gender varchar(10) NULL,
	aadhardob int8 NULL DEFAULT 0,
	user_documents jsonb NULL,
	user_banks jsonb NULL,
	user_qualifications jsonb NULL,
	applicationnumber varchar(50) NULL,
	machineid int8 NULL,
	courseid int8 NULL,
	optedid int8 NULL,
	applicationstatus bool NULL,
	verificationstatus bool NULL,
	firstapprovalstatus bool NULL,
	randomselection bool NULL,
	finalapproval bool NULL,
	submitted bool NULL,
	agreetopay bool NULL,
	"statement" bool NULL,
	userid int8 NULL,
	tenantid varchar(255) NULL,
	createdon int8 NULL,
	createdby varchar(255) NULL,
	modifiedon int8 NULL,
	modifiedby varchar(255) NULL,
	casteid int4 NULL,
	religionid int4 NULL,
	divyangcardid varchar(255) NULL,
	divyangpercent float8 NULL,
	transgenderid varchar(255) NULL,
	divyangid int4 NULL,
	rationcardcategory varchar(255) NULL,
	udid varchar(255) NULL,
	"zone" varchar(50) NULL,
	block varchar(50) NULL,
	ward varchar(50) NULL,
	occupation varchar(255) NULL,
	income float8 NULL,
	CONSTRAINT eg_bmc_application_snapshot_pkey PRIMARY KEY (id),
	CONSTRAINT uni_application_snapshot UNIQUE (userid, tenantid, applicationnumber)
);


ALTER TABLE IF EXISTS eg_bmc_aadharuser
ALTER COLUMN gender TYPE VARCHAR(20);
